apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-eynw
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0047-tenant/tkrw-pr712-0075-0047-app/devfile-sample-eynw@sha256:dd05e8751df4f62ee19d269d80867ac8bf3e9f3a3e60c49a817d139bcf05c868
        name: my-nodejs
        resources: {}
status: {}
